# Create and run a local RAG pipeline from scratch

## What is RAG?

**RAG** stands for Retrieval-Augmented Generation.

The goal of RAG is to take information and pass it to an LLM so it can generate outputs based on that info.

* **Retrieval** - Find relevant information given a query, e.g. "what are macronutrients?" -> retrieve passages of text related to macronutrients.
* **Augmented** - We want to take the relevant info from retrieval and augment our input (prompt) to an LLM with that information.
* **Generation** -  Take the first two steps and pass them to an LLM for generative outputs.

## Why RAG?

The main goal of RAG is to improve the generation outputs of LLMs.

1. Prevent hallucinations - LLMs are good at generation good looking text, but that does not mean that it is factually correct.
    * RAG can help LLMs generate information based on relevant passages that are factual
2. Work with custom data - Many base LLMs are trained with internet-scale data (means good understanding with language in general), but means the responses can be generic in nature.
    * RAG helps create specific responses based on specific documents

## Overview of the RAG pipeline

1. Open a PDF document.
2. Format the text of the PDF textbook ready for an embedding model.
3. Embed all the chunks of text in the textbook and turn them into numerical representations which can be stored for use later.
4. Build a retrieval that uses vector search to find relevant chunks of text given a query.
5. Create a prompt that incorporates the retrieved pieces of text.
6. Generate an answer to the query based on the passages of the textbook that were retrieved with an LLM.

**Steps 1-3:** Document preprocessing and embedding creation

**Steps 4-6:** Retrieval and generation (search and answer)

## 1. Document/text processing

Items needed:
* PDF document of choice

Steps:
1. Import the PDF document
2. Process text for embedding (e.g. split into chunks of sentences)

### Import PDF document

In [1]:
import os # file path handling
import requests # download things off the internet

# Get PDF document path
pdf_path = "human-nutrition-text.pdf"

# Download pdf
if not os.path.exists(pdf_path):
    print(f"[INFO] File doesn't exist, downloading...")

    # URL of pdf
    url = "https://pressbooks.oer.hawaii.edu/humannutrition2/open/download?type=pdf"

    # local filename
    filename = pdf_path

    # Send a GET request to the URL
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        # Open the file and save it
        with open(filename, "wb") as file:
            file.write(response.content)
        
        print(f"[INFO] The file has been downloaded and saved as {filename}")
    else:
        print(f"[ERR] Failed to download file. Status code: {response.status_code}")
else:
    print(f"[INFO] File {pdf_path} already exists.")

[INFO] File human-nutrition-text.pdf already exists.

### Open PDF

In [2]:
import fitz # PyMuPDF -> used to read pdf files
from tqdm.auto import tqdm # progress bars

def text_formatter(text: str) -> str:
    """Performs minor formatting on text"""
    
    # remove newlines and extra whitespace chars
    cleaned_text = text.replace("\n", " ").strip()

    return cleaned_text

def read_pdf(path: str) -> list[dict]:
    doc = fitz.open(path)

    pages = []

    # Loop through all the pages in the pdf
    for page_num, page in tqdm(enumerate(doc)):
        text = page.get_text() # get text of current page
        text = text_formatter(text) # format text

        # append all important info about the current page
        pages.append({
            "page_number" : page_num - 41,
            "char_count": len(text),
            "word_count": len(text.split(" ")),
            "sentence_count": len(text.split(". ")),
            "token_count": len(text) / 4, # 1 token ~= 4 chars
            "text": text
        })

    return pages

#### Key term

| Term | Description |
| ----- | ----- | 
| **Token** | A sub-word piece of text. For example, "hello, world!" could be split into ["hello", ",", "world", "!"]. A token can be a whole word,<br> part of a word or group of punctuation characters. 1 token ~= 4 characters in English, 100 tokens ~= 75 words.<br> Text gets broken into tokens before being passed to an LLM. |

In [3]:
pages = read_pdf(path=pdf_path)

import random

random.sample(pages, k=3)

0it [00:00, ?it/s]

[{'page_number': 312,
  'char_count': 748,
  'word_count': 125,
  'sentence_count': 5,
  'token_count': 187.0,
  'text': 'Learning Activities  Technology Note: The second edition of the Human  Nutrition Open Educational Resource (OER) textbook  features interactive learning activities.  These activities are  available in the web-based textbook and not available in the  downloadable versions (EPUB, Digital PDF, Print_PDF, or  Open Document).  Learning activities may be used across various mobile  devices, however, for the best user experience it is strongly  recommended that users complete these activities using a  desktop or laptop computer and in Google Chrome.    An interactive or media element has been  excluded from this version of the text. You can  view it online here:  http://pressbooks.oer.hawaii.edu/ humannutrition2/?p=212    312  |  How Lipids Work'},
 {'page_number': 1101,
  'char_count': 1786,
  'word_count': 314,
  'sentence_count': 20,
  'token_count': 446.5,
  'text': 'the Centers for Disease Control and Prevention (CDC), heart disease  is the leading cause of death in the United States.2  The disease generally starts with atherosclerosis, or a hardening  of the arteries, a chronic condition so common that most people  show signs of it by the time they turn thirty. Arteries start to narrow  and harden when fats accumulate along their inner walls and form  plaques. A plaque is made of fat, cholesterol, calcium, and other  substances found in blood.  Plaque formation causes arteries to narrow and harden, which  elevates blood pressure because the vessels can’t expand effectively  to accommodate blood pulses. Higher blood pressure strains the  heart and causes more damage. Arterial walls can become so  weakened due to high blood pressure that they balloon and form  what is known as an aneurysm. If the aneurysm bursts, it becomes a  life-threatening event. The plaques themselves can also rupture due  to a spike in blood pressure or a tremor along an arterial wall, and  the body responds to this perceived injury by forming blood clots.  These clots are serious health threats, whether they are stationary  (a thrombus) or moving (an embolus). A stable clot can slowly kill off  surrounding tissue, or grow so big that it blocks blood circulation  and causes thrombosis. When a moving clot becomes stuck in an  artery too small for its passage, it cuts off blood flow and causes cell  death. This is referred to as an embolism. Blood clots in heart and  brain arteries can cause heart attacks or strokes.  Table 18.2 The Risk Factors for Cardiovascular Disease  2. Leading Causes of Death. CDC.gov.  https://www.cdc.gov/nchs/fastats/leading-causes-of- death.htm. Updated March 17, 2017. Accessed April 15,  2018.  Threats to Health  |  1101'},
 {'page_number': 953,
  'char_count': 1383,
  'word_count': 246,
  'sentence_count': 10,
  'token_count': 345.75,
  'text': 'Image by  Allison  Calabrese /  CC BY 4.0  The fuel sources for anaerobic and aerobic metabolism will change  depending on the amount of nutrients available and the type of  metabolism. Glucose may come from blood glucose (which is from  dietary carbohydrates or liver glycogen and glucose synthesis) or  muscle glycogen. Glucose is the primary energy source for both  anaerobic and aerobic metabolism. Fatty acids are stored as  triglycerides in muscles but about 90% of stored energy is found  in adipose tissue. As low to moderate intensity exercise continues  using aerobic metabolism, fatty acids become the predominant fuel  source for the exercising muscles. Although protein is not  considered a major energy source, small amounts of amino acids  are used while resting or doing an activity.  The amount of amino  acids used for energy metabolism increase if the total energy intake  from your diet does not meet the nutrient needs or if you are  involved in long endurance exercises. When amino acids are broken  down removing the nitrogen-containing amino acid, that remaining  carbon molecule can be broken down into ATP via aerobic  metabolism or used to make glucose. When exercise continues for  many hours, amino acid use will increase as an energy source and  for glucose synthesis.  Figure 16.5 Fuel Sources for Anaerobic and Aerobic Metabolism  Fuel Sources  |  953'}]

In [4]:
import pandas as pd

df = pd.DataFrame(pages) # convert the dict into a dataframe
df.head()

,page_number,char_count,word_count,sentence_count,token_count,text
0,-41,29,4,1,7.25,Human Nutrition: 2020 Edition
1,-40,0,1,1,0.00,
2,-39,320,54,1,80.00,Human Nutrition: 2020 Edition UNIVERSITY OF ...
3,-38,212,32,1,53.00,Human Nutrition: 2020 Edition by University of...
4,-37,797,147,3,199.25,Contents Preface University of Hawai‘i at Mā...

In [5]:
df.describe().round(2) # generate a statistical summary of the data

       page_number  char_count  word_count  sentence_count  token_count
count      1208.00     1208.00     1208.00         1208.00      1208.00
mean        562.50     1148.00      199.50           10.52       287.00
std         348.86      560.38       95.83            6.55       140.10
min         -41.00        0.00        1.00            1.00         0.00
25%         260.75      762.00      134.00            5.00       190.50
50%         562.50     1231.50      216.00           10.00       307.88
75%         864.25     1603.50      272.00           15.00       400.88
max        1166.00     2308.00      430.00           39.00       577.00

#### Why does the token count matter?

Token count is important to think about because:
1. Embedding models don't deal with infinite tokens.
2. LLMs don't deal with infinite tokens.

The embedding model we will use (`all-mpnet-base-v2`) is trained to embed sequences of 384 tokens.

As for LLMs, they can't accept infinite tokens in their **context window**.

#### Key term

| Term | Description |
| ----- | ----- | 
| **LLM context window** | The number of tokens a LLM can accept as input. For example, as of March 2024, GPT-4 has a default context window of 32k tokens<br> (about 96 pages of text) but can go up to 128k if needed. A recent open-source LLM from Google, Gemma (March 2024) has a context<br> window of 8,192 tokens (about 24 pages of text). A higher context window means an LLM can accept more relevant information<br> to assist with a query. For example, in a RAG pipeline, if a model has a larger context window, it can accept more reference items<br> from the retrieval system to aid with its generation. |

### Preprocess text for chunking

Split pages into sentences by either:
1. Splitting on `". "`
2. Use NLP library (e.g. `spaCy` and `nltk`)

In [6]:
from spacy.lang.en import English

nlp = English() # create a blank English NLP model

# Add a sentencizer pipeline -> turns text into sentences
nlp.add_pipe("sentencizer")

# Create a document instance as an example
doc = nlp("This is the first sentence. This is the second sentence. I like cats.")
assert len(list(doc.sents)) == 3

# Print out the sentences split
list(doc.sents)

[This is the first sentence., This is the second sentence., I like cats.]

In [7]:
pages[67]

{'page_number': 26,
 'char_count': 1799,
 'word_count': 321,
 'sentence_count': 21,
 'token_count': 449.75,
 'text': 'Factors that Drive Food Choices  Along with these influences, a number of other factors affect the  dietary choices individuals make, including:  • Taste, texture, and appearance. Individuals have a wide range  of tastes which influence their food choices, leading some to  dislike milk and others to hate raw vegetables. Some foods that  are very healthy, such as tofu, may be unappealing at first to  many people. However, creative cooks can adapt healthy foods  to meet most people’s taste.  • Economics. Access to fresh fruits and vegetables may be scant,  particularly for those who live in economically disadvantaged  or remote areas, where cheaper food options are limited to  convenience stores and fast food.  • Early food experiences. People who were not exposed to  different foods as children, or who were forced to swallow  every last bite of overcooked vegetables, may make limited  food choices as adults.  • Habits. It’s common to establish eating routines, which can  work both for and against optimal health. Habitually grabbing a  fast food sandwich for breakfast can seem convenient, but  might not offer substantial nutrition. Yet getting in the habit of  drinking an ample amount of water each day can yield multiple  benefits.  • Culture. The culture in which one grows up affects how one  sees food in daily life and on special occasions.  • Geography. Where a person lives influences food choices. For  instance, people who live in Midwestern US states have less  access to seafood than those living along the coasts.  • Advertising. The media greatly influences food choice by  persuading consumers to eat certain foods.  • Social factors. Any school lunchroom observer can testify to  the impact of peer pressure on eating habits, and this  26  |  Lifestyles and Nutrition'}

In [8]:
for item in tqdm(pages):
    # Apply the pipeline to the text and get the sentences
    item["sentences"] = list(nlp(item["text"]).sents)

    # Convert all sentences to strings (default is a spaCy datatype)
    item["sentences"] = [str(sentence) for sentence in item["sentences"]]

    # Count the sentences
    item["sentence_count_spacy"] = len(item["sentences"])

  0%|          | 0/1208 [00:00<?, ?it/s]

In [9]:
random.sample(pages, k=1)

[{'page_number': 522,
  'char_count': 1957,
  'word_count': 351,
  'sentence_count': 14,
  'token_count': 489.25,
  'text': 'are packaged into the lipid-containing chylomicrons inside small  intestine mucosal cells and then transported to the liver. In the liver,  carotenoids are repackaged into lipoproteins, which transport them  to cells.  The retinoids are aptly named as their most notable function is  in the retina of the eye where they aid in vision, particularly in  seeing under low-light conditions. This is why night blindness is the  most definitive sign of vitamin A deficiency.Vitamin A has several  important functions in the body, including maintaining vision and a  healthy immune system. Many of vitamin A’s functions in the body  are similar to the functions of hormones (for example, vitamin A can  interact with DNA, causing a change in protein function). Vitamin A  assists in maintaining healthy skin and the linings and coverings of  tissues; it also regulates growth and development. As an antioxidant,  vitamin A protects cellular membranes, helps in maintaining  glutathione levels, and influences the amount and activity of  enzymes that detoxify free radicals.  Vision  Retinol that is circulating in the blood is taken up by cells in the  eye retina, where it is converted to retinal and is used to help  the pigment rhodopsin, which is involved in the eye’s ability to see  under low light conditions. A deficiency in vitamin A thus results in  less rhodopsin and a decrease in the detection of low-level light, a  condition referred to as night-blindness.  Insufficient intake of dietary vitamin A over time can also cause  complete vision loss. In fact, vitamin A deficiency is the number  one cause of preventable blindness worldwide. Vitamin A not only  supports the vision function of eyes but also maintains the  coverings and linings of the eyes. Vitamin A deficiency can lead to  the dysfunction of the linings and coverings of the eye (eg. bitot  spots),  causing  dryness  of  the  eyes,  a  condition  called  522  |  Fat-Soluble Vitamins',
  'sentences': ['are packaged into the lipid-containing chylomicrons inside small  intestine mucosal cells and then transported to the liver.',
   'In the liver,  carotenoids are repackaged into lipoproteins, which transport them  to cells.',
   ' The retinoids are aptly named as their most notable function is  in the retina of the eye where they aid in vision, particularly in  seeing under low-light conditions.',
   'This is why night blindness is the  most definitive sign of vitamin A deficiency.',
   'Vitamin A has several  important functions in the body, including maintaining vision and a  healthy immune system.',
   'Many of vitamin A’s functions in the body  are similar to the functions of hormones (for example, vitamin A can  interact with DNA, causing a change in protein function).',
   'Vitamin A  assists in maintaining healthy skin and the linings and coverings of  tissues; it also regulates growth and development.',
   'As an antioxidant,  vitamin A protects cellular membranes, helps in maintaining  glutathione levels, and influences the amount and activity of  enzymes that detoxify free radicals.',
   ' Vision  Retinol that is circulating in the blood is taken up by cells in the  eye retina, where it is converted to retinal and is used to help  the pigment rhodopsin, which is involved in the eye’s ability to see  under low light conditions.',
   'A deficiency in vitamin A thus results in  less rhodopsin and a decrease in the detection of low-level light, a  condition referred to as night-blindness.',
   ' Insufficient intake of dietary vitamin A over time can also cause  complete vision loss.',
   'In fact, vitamin A deficiency is the number  one cause of preventable blindness worldwide.',
   'Vitamin A not only  supports the vision function of eyes but also maintains the  coverings and linings of the eyes.',
   'Vitamin A deficiency can lead to  the dysfunction of the linings and coverings of the eye (eg.',
   'bitot  spots),  causing  dryness  of  the  eyes,  a  condition  called  522  |  Fat-Soluble Vitamins'],
  'sentence_count_spacy': 15}]

In [10]:
df = pd.DataFrame(pages)
df.describe().round(2)

,page_number,char_count,word_count,sentence_count,token_count,sentence_count_spacy
count,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,199.50,10.52,287.00,10.32
std,348.86,560.38,95.83,6.55,140.10,6.30
min,-41.00,0.00,1.00,1.00,0.00,0.00
25%,260.75,762.00,134.00,5.00,190.50,5.00
50%,562.50,1231.50,216.00,10.00,307.88,10.00
75%,864.25,1603.50,272.00,15.00,400.88,15.00
max,1166.00,2308.00,430.00,39.00,577.00,28.00

### Chunking

The concept of splitting larger pieces of text into smaller ones is often referred to as text splitting or chunking.

We do this because:
1. Texts are easier to filter (smaller groups are easier to inspect)
2. So text chunks can fit into the embedding model context window (e.g. 384 token limit)
3. The contexts passed to the LLM can be more specific and focused

We will split it into groups of 10 sentences (could also try 5, 7, 8, etc.)

Libraries such as `LangChain` could help with this.

In [11]:
# Define split size to turn groups of sentences into chunks
chunk_size = 10

# Create a function that splits lists of texts recursively into chunk size
# e.g. [20] -> [10, 10]
# e.g. [25] -> [10, 10, 5] (basically do chunk_size until we run out)
def split_list(text: list[str], slice_size: int=chunk_size) -> list[list[str]]:
    return [text[i:i+slice_size] for i in range(0, len(text), slice_size)]

# Test
test_list = list(range(25))
split_list(test_list)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [12]:
# Loop through pages and split the sentences into chunks
for item in tqdm(pages):
    # Use the prev. defined function to split the sentences into chunks of 10
    item["sentence_chunks"] = split_list(item["sentences"],
                                         slice_size=chunk_size)
    
    item["num_chunks"] = len(item["sentence_chunks"]) # how many chunks there are

  0%|          | 0/1208 [00:00<?, ?it/s]

In [13]:
random.sample(pages, k=1)

[{'page_number': 526,
  'char_count': 1383,
  'word_count': 235,
  'sentence_count': 14,
  'token_count': 345.75,
  'text': 'higher incidence of lung cancer midway through the study, which  was consequently stopped.2  Vitamin A Toxicity  Vitamin A toxicity, or hypervitaminosis A, is rare. Typically it  requires you to ingest ten times the RDA of preformed vitamin A in  the form of supplements (it would be hard to consume such high  levels from a regular diet) for a substantial amount of time, although  some people may be more susceptible to vitamin A toxicity at lower  doses. The signs and symptoms of vitamin A toxicity include dry,  itchy skin, loss of appetite, swelling of the brain, and joint pain. In  severe cases, vitamin A toxicity may cause liver damage and coma.  Vitamin A is essential during pregnancy, but doses above 3,000  micrograms per day (10,000 international units) have been linked  to an increased incidence of birth defects. Pregnant women should  check the amount of vitamin A contained in any prenatal or  pregnancy multivitamin she is taking to assure the amount is below  the UL.  2. Goodman GE, et al. (2004). The Beta-Carotene and  Retinol Efficacy Trial: Incidence of Lung Cancer and  Cardiovascular Disease Mortality During 6-year Follow- up after Stopping Beta-Carotene and Retinol  Supplements. Journal of the National Cancer  Institute, 96(23), 1743–50. http://jnci.oxfordjournals.org/ content/96/23/1743.long. Accessed October 6, 2017.  526  |  Fat-Soluble Vitamins',
  'sentences': ['higher incidence of lung cancer midway through the study, which  was consequently stopped.2  Vitamin A Toxicity  Vitamin A toxicity, or hypervitaminosis A, is rare.',
   'Typically it  requires you to ingest ten times the RDA of preformed vitamin A in  the form of supplements (it would be hard to consume such high  levels from a regular diet) for a substantial amount of time, although  some people may be more susceptible to vitamin A toxicity at lower  doses.',
   'The signs and symptoms of vitamin A toxicity include dry,  itchy skin, loss of appetite, swelling of the brain, and joint pain.',
   'In  severe cases, vitamin A toxicity may cause liver damage and coma.',
   ' Vitamin A is essential during pregnancy, but doses above 3,000  micrograms per day (10,000 international units) have been linked  to an increased incidence of birth defects.',
   'Pregnant women should  check the amount of vitamin A contained in any prenatal or  pregnancy multivitamin she is taking to assure the amount is below  the UL.',
   ' 2.',
   'Goodman GE, et al. (',
   '2004).',
   'The Beta-Carotene and  Retinol Efficacy Trial: Incidence of Lung Cancer and  Cardiovascular Disease Mortality During 6-year Follow- up after Stopping Beta-Carotene and Retinol  Supplements.',
   'Journal of the National Cancer  Institute, 96(23), 1743–50.',
   'http://jnci.oxfordjournals.org/ content/96/23/1743.long.',
   'Accessed October 6, 2017.',
   ' 526  |  Fat-Soluble Vitamins'],
  'sentence_count_spacy': 14,
  'sentence_chunks': [['higher incidence of lung cancer midway through the study, which  was consequently stopped.2  Vitamin A Toxicity  Vitamin A toxicity, or hypervitaminosis A, is rare.',
    'Typically it  requires you to ingest ten times the RDA of preformed vitamin A in  the form of supplements (it would be hard to consume such high  levels from a regular diet) for a substantial amount of time, although  some people may be more susceptible to vitamin A toxicity at lower  doses.',
    'The signs and symptoms of vitamin A toxicity include dry,  itchy skin, loss of appetite, swelling of the brain, and joint pain.',
    'In  severe cases, vitamin A toxicity may cause liver damage and coma.',
    ' Vitamin A is essential during pregnancy, but doses above 3,000  micrograms per day (10,000 international units) have been linked  to an increased incidence of birth defects.',
    'Pregnant women should  check the amount of vitamin A contained in any prenatal or  pregnancy multivitamin she is taking to assure the amount is below  the UL.',
    ' 2.',
    'Goodman GE, et al. (',
    '2004).',
    'The Beta-Carotene and  Retinol Efficacy Trial: Incidence of Lung Cancer and  Cardiovascular Disease Mortality During 6-year Follow- up after Stopping Beta-Carotene and Retinol  Supplements.'],
   ['Journal of the National Cancer  Institute, 96(23), 1743–50.',
    'http://jnci.oxfordjournals.org/ content/96/23/1743.long.',
    'Accessed October 6, 2017.',
    ' 526  |  Fat-Soluble Vitamins']],
  'num_chunks': 2}]

In [14]:
df = pd.DataFrame(pages)
df.describe().round(2)

,page_number,char_count,word_count,sentence_count,token_count,sentence_count_spacy,num_chunks
count,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,199.50,10.52,287.00,10.32,1.53
std,348.86,560.38,95.83,6.55,140.10,6.30,0.64
min,-41.00,0.00,1.00,1.00,0.00,0.00,0.00
25%,260.75,762.00,134.00,5.00,190.50,5.00,1.00
50%,562.50,1231.50,216.00,10.00,307.88,10.00,1.00
75%,864.25,1603.50,272.00,15.00,400.88,15.00,2.00
max,1166.00,2308.00,430.00,39.00,577.00,28.00,3.00

### Split each chunk into its own dictionary item

We want to embed each chunk of sentences into its own numerical representation.

Meaning, we can dive specifically into the text sample that is relevant to a query.

In [15]:
import re # regex

# Split each chunk into its own item
chunks = []

# Loop through all the pages
for item in tqdm(pages):
    # Loop through all the chunks for the current page
    for sentence_chunk in item["sentence_chunks"]:
        chunk_dict = {}

        # Get current chunk's page number
        chunk_dict["page_number"] = item["page_number"]

        # Join the lists of sentences back into together into a single paragraph
        joined_sentences = "".join(sentence_chunk).replace("  ", " ").strip() # remove extra spaces
        joined_sentences = re.sub(r'\.([A-Z])', r'. \1', joined_sentences) # ".A" -> ". A"
        
        # Add the paragraph into the dict
        chunk_dict["sentence_chunk"] = joined_sentences

        # Add some stats of the chunks
        chunk_dict["chunk_char_count"] = len(joined_sentences)
        chunk_dict["chunk_word_count"] = len([word for word in joined_sentences.split(" ")])
        chunk_dict["chunk_token_count"] = len(joined_sentences) / 4 # 1 token = 4 chars

        chunks.append(chunk_dict)

len(chunks) # how many chunks there are in total

  0%|          | 0/1208 [00:00<?, ?it/s]

1843

In [16]:
random.sample(chunks, k=1)

[{'page_number': 165,
  'sentence_chunk': 'Percentage Food Item 90–99 Nonfat milk, cantaloupe, strawberries, watermelon, lettuce, cabbage, celery, spinach, squash 80–89 Fruit juice, yogurt, apples, grapes, oranges, carrots, broccoli, pears, pineapple 70–79 Bananas, avocados, cottage cheese, ricotta cheese, baked potato, shrimp 60–69 Pasta, legumes, salmon, chicken breast 50–59 Ground beef, hot dogs, steak, feta cheese 40–49 Pizza 30–39 Cheddar cheese, bagels, bread 20–29 Pepperoni, cake, biscuits 10–19 Butter, margarine, raisins 1–9 Walnuts, dry-roasted peanuts, crackers, cereals, pretzels, peanut butter 0 Oils, sugars Source: National Nutrient Database for Standard Reference, Release 23. US Department of Agriculture, Agricultural Research Service. http://www.ars.usda.gov/ba/bhnrc/ndl. Updated 2010. Accessed September 2017. There is some debate over the amount of water required to maintain health because there is no consistent scientific evidence proving that drinking a particular amount of water improves health or reduces the risk of disease. In fact, kidney-stone prevention seems to be the only premise for water-consumption recommendations. You may be surprised to find out that the commonly held belief that people need to drink eight 8-ounce glasses of water per day isn’t an official recommendation and isn’t based on any scientific evidence!The amount of water/fluids a person should consume every day is actually variable and should be based on the climate a person lives in, as well as their age, physical activity level, and kidney function. No maximum for water intake has been set.',
  'chunk_char_count': 1567,
  'chunk_word_count': 224,
  'chunk_token_count': 391.75}]

In [17]:
df = pd.DataFrame(chunks)
df.describe().round(2)

       page_number  chunk_char_count  chunk_word_count  chunk_token_count
count      1843.00           1843.00           1843.00            1843.00
mean        583.38            734.10            112.74             183.52
std         347.79            447.51             71.24             111.88
min         -41.00             12.00              3.00               3.00
25%         280.50            315.00             45.00              78.75
50%         586.00            745.00            115.00             186.25
75%         890.00           1118.00            173.00             279.50
max        1166.00           1830.00            297.00             457.50

### Filter out short chunks

These chunks may be too short to be useful for embedding and retrieval. We can filter them out by checking the number of tokens in each chunk.

In [18]:
# Show random chunks with under 30 tokens (mostly contain headers or links)

min_token_len = 30

# Create a filtered df that contains only the short chunks and loop through the rows
for _, r in df[df["chunk_token_count"] <= min_token_len].sample(5).iterrows():
    # Display the current rows token count and its text
    print(f"Chunk token count: {r['chunk_token_count']} | Text: {r['sentence_chunk']}")

Chunk token count: 16.0 | Text: PART II CHAPTER 2. THE HUMAN BODY Chapter 2. The Human Body | 53
Chunk token count: 27.75 | Text: In exchange, for the reabsorption of sodium and water, potassium is excreted. Regulation of Water Balance | 169
Chunk token count: 9.75 | Text: 920 | Older Adulthood: The Golden Years
Chunk token count: 23.0 | Text: view it online here: http://pressbooks.oer.hawaii.edu/ humannutrition2/?p=301 The Atom | 471
Chunk token count: 20.5 | Text: PART XVI CHAPTER 16. PERFORMANCE NUTRITION Chapter 16. Performance Nutrition | 931

In [19]:
# Filter the dataframe for rows with under 30 tokens

# convert the custom df with chunks passing the min token limit into a dictionary
chunks_over_min_token_len = df[df["chunk_token_count"] > min_token_len].to_dict(orient="records")

random.sample(chunks_over_min_token_len, k=1)

[{'page_number': 135,
  'sentence_chunk': 'Caucasians face greater health risks for the same BMI than African Americans. Calculating BMI To calculate your BMI, multiply your weight in pounds by 703 (conversion factor for converting to metric units) and then divide the product by your height in inches, squared. BMI = [weight (lb) x 703] ÷ height (in)2 or BMI = [weight (kg)] ÷ height (m)2 More Ways to Calculate The National Heart, Lung, and Blood Institute and the CDC have automatic BMI calculators on their websites: • https://www.nhlbisupport.com/bmi/ • https://www.cdc.gov/healthyweight/assessing/bmi/ adult_bmi/english_bmi_calculator/bmi_calculator.html To see how your BMI indicates the weight category you are in, see Table 2.3 “BMI Categories”. Table 2.3 BMI Categories Categories BMI Underweight < 18.5 Healthy or Normal weight 18.5–24.9 Overweight 25–29.9 Obese > 30.0 Indicators of Health: Body Mass Index, Body Fat Content, and Fat Distribution | 135',
  'chunk_char_count': 921,
  'chunk_word_count': 136,
  'chunk_token_count': 230.25}]

## 2. Embedding creation

Items needed:
* Embedding moodel of choice

Steps:
1. Embed text chunks with embedding model
2. Save embeddings to a file for later retrieval

**Embeddings** are a broad but powerful concept. While humans understand text, machines understand numbers.

Goal:
- Turn the text chunks into numbers, specifically embeddings (useful numerical representation)

The best part about embeddings is that they are a learned representation.

### Import embedding model

In [20]:
from  sentence_transformers import SentenceTransformer # import the embedding model from huggingface

# Model that will be used
model_name = "all-mpnet-base-v2"

model = SentenceTransformer(model_name_or_path=model_name,
                            device="cpu")

# Create a list of sentences to test the model
sentences = ["The Sentence Transformer library provides an easy way to create embeddings",
             "Sentences can be embedded one by one or in a list",
             "I like cats"]

# Encode/embed the sentences using model.encode()
embeddings = model.encode(sentences)

embeddings_dict = dict(zip(sentences, embeddings))

# Print the embeddings
for sentence, embedding in embeddings_dict.items():
    print(f"Sentence: {sentence}")
    print(f"Embedding: {embedding} \n")

C:\Users\ranic\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
C:\Users\ranic\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Sentence: The Sentence Transformer library provides an easy way to create embeddings
Embedding: [-3.17512713e-02  3.37267332e-02 -2.52437890e-02  5.22288345e-02
 -2.35249549e-02 -6.19114423e-03  1.35025214e-02 -6.25500977e-02
  7.50832073e-03 -2.29684841e-02  2.98146065e-02  4.57555354e-02
 -3.26700285e-02  1.39847193e-02  4.18013632e-02 -5.92969768e-02
  4.26310301e-02  5.04657347e-03 -2.44552437e-02  3.98591254e-03
  3.55898067e-02  2.78742649e-02  1.84098873e-02  3.67699340e-02
 -2.29961537e-02 -3.01796701e-02  5.99592924e-04 -3.64504047e-02
  5.69104850e-02 -7.49938935e-03 -3.70004512e-02 -3.04365251e-03
  4.64354679e-02  2.36154278e-03  9.06849607e-07  7.00036483e-03
 -3.92289385e-02 -5.95699111e-03  1.38653489e-02  1.87108992e-03
  5.34202717e-02 -6.18613325e-02  2.19613481e-02  4.86051440e-02
 -4.25697304e-02 -1.69858746e-02  5.04178256e-02  1.54733444e-02
  8.12860206e-02  5.07106483e-02 -2.27496885e-02 -4.35720906e-02
 -2.18387460e-03 -2.14091651e-02 -2.01758165e-02  3.06832269e-02
 -3.51334326e-02 -1.37516009e-02 -1.47074712e-02  3.83924358e-02
 -3.63251045e-02  4.24920395e-02  6.66143466e-03 -3.98761816e-02
  7.14551732e-02 -1.35859177e-02 -6.60983771e-02 -8.44915211e-03
  4.74621914e-03  6.11576699e-02  2.99040577e-03 -2.55231205e-02
 -3.34805921e-02 -8.53998400e-03  3.12245656e-02  2.98417136e-02
 -4.85905632e-02 -1.11949369e-02  7.23602474e-02  3.28174122e-02
  1.77803857e-03  5.02722114e-02  2.30483748e-02 -4.10619751e-02
 -3.49084139e-02 -4.36537340e-02  5.07546440e-02 -4.66824472e-02
 -3.67541201e-02 -2.16351394e-02 -8.07572715e-03  2.78772321e-02
  3.41444276e-02 -2.42736991e-02  9.37790982e-03  1.27494680e-02
 -7.16165230e-02 -3.23407687e-02 -8.06690753e-03 -2.30582561e-02
  6.39590919e-02  1.22526279e-02 -1.84588833e-03  4.58423467e-03
 -8.37132260e-02  6.05703369e-02 -3.02917603e-03 -4.53535793e-03
 -2.79873386e-02 -2.37172171e-02 -4.24652100e-02 -1.20252045e-02
 -6.66096658e-02  6.39967667e-03 -1.92155950e-02 -6.99942112e-02
 -4.53624763e-02  5.89808859e-02 -3.09234038e-02  2.02953741e-02
  1.01700248e-02  1.30998502e-02  7.79713690e-03  2.21275464e-02
 -9.14814789e-03  1.98615622e-02 -2.74215993e-02 -2.36939546e-02
 -2.22199280e-02  2.53693294e-02 -3.28815877e-02  5.13044521e-02
  6.19513057e-02 -7.44251115e-03 -4.78575751e-02  9.91808344e-03
  1.66845843e-02 -3.57198305e-02  3.01708877e-02  4.00398076e-02
 -5.39108738e-03  1.51401404e-02  5.59857441e-03 -4.78387401e-02
  6.58323467e-02  2.69618700e-03  1.13033475e-02 -4.28623222e-02
  2.22742967e-02  2.74195652e-02 -5.09938002e-02  1.17162704e-01
  1.34981629e-02 -3.71388309e-02 -6.41476884e-02 -2.63015945e-02
  7.84799457e-02  5.48545457e-02  5.46070784e-02 -9.82332602e-03
  5.09111397e-02 -3.13048688e-04 -6.86396752e-03  1.70785263e-02
 -1.35588422e-02 -2.16211914e-03 -2.34771781e-02 -1.55508900e-02
 -8.23162438e-04  8.29926506e-02 -9.48116183e-03  7.00236186e-02
  3.33339348e-03  1.47000467e-02  2.84736156e-02  6.13352545e-02
  6.53134435e-02  1.27843162e-02  8.42677429e-02  2.58606728e-02
 -3.99191901e-02  2.62350496e-02 -3.68678421e-02  5.22657372e-02
  1.86432954e-02  3.53657454e-02 -2.45989729e-02  8.81066024e-02
  2.55999924e-03  5.99745708e-03 -2.03187857e-02 -3.80547866e-02
  1.56885460e-02 -4.86830696e-02 -1.02307517e-02  5.31377457e-02
 -3.93920764e-02  5.00219017e-02 -4.20135399e-03 -6.84148297e-02
 -8.43474083e-03  3.83050777e-02  3.40063148e-03  6.75314069e-02
  4.67102416e-02  1.85773708e-02  1.75162777e-02 -3.13067548e-02
 -3.83051522e-02  8.36634189e-02  3.01607735e-02 -1.63155254e-02
 -2.75369026e-02 -7.45282173e-02  3.94692272e-02 -1.40263917e-04
  1.06907114e-02 -2.64681317e-02 -9.52936616e-03  2.35250313e-02
  6.30770400e-02 -3.58119868e-02  3.75604182e-02  3.86091098e-02
 -2.86414400e-02 -2.03893818e-02  3.76560376e-03  2.92671621e-02
  1.12931160e-02  3.38566452e-02 -1.25357145e-02  6.60268292e-02
  6.35566637e-02 -4.86964807e-02 -4.31395136e-02  6.28765151e-02
 -2.69191992e-02 -8.75512436e-02  8.27585906e-03 -1.02666572e-01
  2.47256719e-02  1.35638332e-02 -5.55745373e-03 -1.86810344e-02
 -1.44041469e-02 -8.57950468e-03  8.13291594e-02 -4.46740314e-02
 -4.09445353e-03  3.33538391e-02  4.34364192e-02 -3.02401185e-02
  6.42347010e-03  4.94938344e-02  1.72628220e-02 -2.46238355e-02
 -2.80704834e-02 -1.87670114e-03  4.09032218e-02 -5.85711701e-03
 -1.95791554e-02  1.88910719e-02 -1.10968929e-02 -2.61494424e-02
 -3.96265008e-04  2.14644652e-02 -3.54524814e-02 -5.03614508e-02
  2.74631847e-03  1.68064591e-02 -9.64395329e-03  1.37957791e-02
  2.89547089e-02  1.18163656e-02  3.01219448e-02 -4.64622751e-02
  1.53108109e-02 -6.87962165e-03  2.01097708e-02  4.71905097e-02
 -6.08274192e-02 -4.23219353e-02 -3.57371271e-02  2.87291910e-02
 -2.81012170e-02  6.10911138e-02 -5.18230870e-02 -7.50937359e-03
 -3.07046995e-02  8.13341991e-04  1.45774689e-02  1.22668678e-02
  3.79741602e-02 -4.22005653e-02 -9.40956082e-03  1.26130134e-02
  8.55632871e-02  3.77735011e-02  1.41394604e-03  6.41736314e-02
  5.05688861e-02 -5.77932922e-03 -1.09078540e-02  6.78478787e-03
 -2.00582612e-02  4.89428155e-02 -8.49455222e-03 -2.42431043e-03
 -7.37101072e-03  1.85880084e-02  8.08329321e-03 -1.03385253e-02
 -2.87858434e-02  3.13182324e-02 -3.78198456e-03 -4.82107466e-03
  3.10748466e-03 -3.02714552e-03 -2.93274466e-02 -2.47740578e-02
  3.53626013e-02  5.44227660e-04  3.12252622e-02 -4.56644744e-02
 -3.05787940e-02 -4.38935235e-02 -3.39478813e-02 -4.15794142e-02
  6.44758195e-02 -1.55905483e-03  3.98305664e-03 -2.27167271e-03
 -6.35493640e-03 -3.55863497e-02  2.65947897e-02  4.69325036e-02
  1.64104458e-02  1.79546811e-02  1.33658759e-02 -2.66936980e-02
 -2.39923354e-02 -2.06165239e-02 -2.48198602e-02 -5.12003861e-02
 -5.54500846e-03  1.81241427e-02  2.81455647e-02 -1.52694443e-02
 -3.62992994e-02  1.41980583e-02 -1.03262803e-02 -1.53739573e-02
 -1.90759879e-02  7.37814885e-03 -4.32781912e-02  6.44605383e-02
  4.22289148e-02  3.69743234e-03 -2.10980233e-02  9.27715446e-04
  7.00220987e-02 -1.28834331e-02 -4.43938375e-02  7.84380734e-03
 -5.62280007e-02 -2.58355048e-02  4.93658660e-03 -4.98834886e-02
  2.39315871e-02 -2.46334472e-04  3.04043153e-03  1.11720460e-02
 -1.84925180e-02  8.85111317e-02  5.27525432e-02 -4.00967188e-02
  3.53580490e-02 -3.67239043e-02  3.67109738e-02  9.71163251e-03
  3.12656611e-02 -1.22500785e-01 -3.10587250e-02 -3.13425506e-03
 -3.61339599e-02  4.28802259e-02  2.79539265e-04  4.80146240e-03
 -9.82156619e-02  2.61312574e-02  1.68510973e-02  4.25127521e-02
 -4.40636538e-02 -1.92942284e-02 -4.17811722e-02  1.10102063e-02
 -1.29304640e-02 -3.19889821e-02 -2.09932979e-02  6.59039989e-03
 -5.12905121e-02 -5.68091013e-02 -1.73662007e-02 -2.85681952e-02
 -5.78577444e-02  3.06151491e-02 -1.91638363e-04  5.92039265e-02
  2.28507747e-03 -3.68659981e-02 -7.59676620e-02 -2.37930678e-02
 -5.88498674e-02  2.44147908e-02  3.55510190e-02 -2.30707601e-02
 -2.64748763e-02  6.83392445e-03  3.58307026e-02 -3.77269089e-02
 -3.35451216e-02  2.75023878e-02  8.47892985e-02 -2.30224594e-03
  5.99637721e-03 -4.39461283e-02  1.90635193e-02  2.43068617e-02
  4.97597493e-02  3.48220840e-02 -1.22427968e-02 -9.52055037e-04
  8.12208652e-03  7.42878951e-03 -4.32638228e-02 -4.86899875e-02
  3.33769284e-02 -9.35189798e-03  4.57262397e-02 -8.49949718e-02
 -3.17019820e-02  5.82109019e-02  2.98860371e-02  3.27124521e-02
  3.13584879e-03  7.53516005e-03  1.71621703e-03 -5.69137298e-02
 -1.17816832e-02  1.43012926e-02  1.84575971e-02  2.41325814e-02
 -1.80390645e-02  5.36695495e-02  3.78649496e-02  1.19281104e-02
 -3.06920968e-02 -3.29276510e-02 -4.37397510e-02  9.22677852e-03
  2.39838623e-02  1.34406285e-02  1.18268924e-02 -3.75343598e-02
  3.63410600e-02  4.29439507e-02  4.53459918e-02 -7.29760602e-02
 -1.10598309e-02  1.17620360e-02 -2.06151810e-02  1.47658810e-02
  3.64490040e-02 -3.24941846e-03  4.32062708e-03 -6.36857599e-02
  4.23910730e-02  1.79280825e-02 -7.00057447e-02  1.53178405e-02
 -5.22550270e-02 -1.89471841e-02 -2.84226052e-02  5.57508832e-03
 -6.22836920e-03  1.74789540e-02 -1.05596527e-01 -3.59372571e-02
 -5.49096093e-02  2.42202021e-02  4.82033677e-02  2.00591069e-02
  1.22003211e-02 -1.89718604e-02 -3.32487822e-02  8.26577656e-03
  3.25941411e-03  6.27234578e-02  4.37995382e-02 -1.64108183e-02
 -1.29950102e-02  2.99947113e-02 -3.55265401e-02 -1.05935009e-02
 -6.53243437e-02 -1.05157262e-02 -3.01193614e-02 -1.06331166e-02
 -1.90696251e-02 -1.08426670e-02 -4.72782366e-02  4.36234213e-02
 -3.26108597e-02  5.00925705e-02 -3.29291075e-02  2.48312298e-03
  7.13982880e-02 -1.29912151e-02  5.38316965e-02 -1.64794158e-02
 -2.57684551e-02  6.63955584e-02  6.69528469e-02 -6.91024885e-02
 -1.29960040e-02  2.54570576e-03  1.08204084e-02 -3.45112942e-02
 -4.18824181e-02  4.11806516e-02 -2.14524027e-02 -1.99218350e-03
  2.75431275e-02  1.97309931e-03 -5.62767014e-02 -1.72102638e-02
  4.73647602e-02  2.71154996e-02 -2.16401462e-02 -1.61213689e-02
 -3.51910889e-02 -6.50478005e-02 -5.54158865e-03  3.18600722e-02
 -9.87859257e-03  1.18842432e-02 -1.54758170e-02  2.12222841e-02
  1.55511824e-02 -1.70723777e-02 -1.55686000e-02  3.15089896e-02
 -1.18929436e-02 -7.12359771e-02 -3.30978222e-02 -4.32606643e-33
 -4.62589040e-02  1.22969551e-02 -3.20229866e-02 -2.78885085e-02
 -1.08435582e-02 -1.10652344e-02  8.93467758e-03  2.52347812e-02
  2.32202411e-02  3.27641107e-02  7.82624539e-03 -2.69480757e-02
  1.19924713e-02  1.65210012e-02 -2.60639470e-03  2.92153787e-02
  2.84571517e-02 -2.02488285e-02  9.00312513e-03  8.76456965e-03
  1.29353395e-02  4.02024053e-02  4.33696434e-02 -2.80213188e-02
 -2.89619248e-02  1.52371451e-02 -8.27927142e-03  2.36236709e-04
  3.45984697e-02  4.76797856e-02 -2.41580904e-02  1.96413379e-02
 -1.51803484e-02  2.42424589e-02 -1.42624322e-02  7.18389228e-02
 -5.58839068e-02 -1.55400047e-02  4.14171293e-02 -1.92339048e-02
 -2.55287550e-02 -4.58723530e-02 -2.71275286e-02 -4.43420373e-02
  3.60834002e-02  5.78192668e-03  3.51143330e-02 -4.16079862e-03
 -8.40502977e-03 -3.97926662e-03 -7.85549209e-02 -2.72270525e-03
  6.03272906e-03  1.87141355e-02  1.59002300e-02 -1.67104488e-04
  2.86227558e-03  6.50430564e-03 -9.02045798e-03 -9.05948412e-03
 -3.17575075e-02  2.61157304e-02  2.27601174e-02 -4.73466069e-02
 -4.33875471e-02  5.98783791e-02 -3.70310917e-02 -3.92582007e-02
 -7.42960349e-03  3.97703536e-02  2.05765944e-02  4.45614718e-02
  5.17226346e-02  6.47155046e-02 -1.12156188e-02  1.98143926e-02
 -1.74945835e-02 -1.85965002e-02  2.05232445e-02  2.25110864e-03
  4.36831154e-02  3.15700583e-02  2.36150157e-02 -1.29921287e-02
 -1.68885794e-02  3.43268318e-03  1.92210922e-04 -6.20984398e-02
  3.11526340e-02  1.04306974e-02 -3.49925980e-02  7.67281139e-03
  3.18957381e-02 -2.56587006e-02  4.89982869e-03  1.79349687e-02
 -1.52581269e-02  2.70325802e-02 -8.59267451e-03  3.45437266e-02
  8.93352181e-03 -3.48193198e-02  1.24014670e-03 -8.79185740e-03
  2.69112624e-02  1.40880570e-02  3.80622149e-02 -9.51180514e-03
 -7.63270855e-02 -1.83740538e-03 -4.29710001e-03 -5.61364852e-02
 -5.31258173e-02  2.93392176e-03 -1.72041226e-02  2.31317785e-02
 -1.01896236e-02 -1.86988234e-03  3.17086913e-02 -6.50319550e-03
 -2.88114715e-02 -2.14221478e-02  3.67089659e-02  3.45961526e-02
 -2.46727634e-02 -1.98293105e-02 -4.26006280e-02  4.03007194e-02
  5.03498055e-02 -6.73352256e-02  1.44803701e-02 -1.37583970e-03
  1.72852523e-07  3.70796062e-02  6.15185052e-02  4.44693752e-02
  6.80549885e-04 -1.33423842e-02 -2.72832010e-02  6.99472195e-03
  6.66199401e-02  2.50304176e-04  2.30059139e-02  1.88476723e-02
 -1.44463023e-02  1.54894758e-02  2.89910752e-02 -1.31518692e-01
  2.14486737e-02 -2.88340915e-02 -2.95150243e-02 -4.65547442e-02
 -1.54500920e-02  1.24013722e-01  1.09433249e-01  4.62636277e-02
  4.23714034e-02 -1.23258093e-02 -2.99533401e-02  3.81512493e-02
  3.16713657e-03 -3.14146653e-02 -1.89234819e-02 -2.20976919e-02
 -2.07271203e-02 -1.20526850e-02 -9.80346650e-03 -2.79675387e-02
  2.28398796e-02  1.71223041e-02  8.59403703e-03  2.80324626e-03
 -1.35171833e-03 -3.63583378e-02 -9.39919055e-03 -1.85964070e-02
 -4.00975011e-02  5.22999614e-02 -8.10100362e-02 -1.47648156e-02
 -3.93798426e-02 -3.35375592e-02  4.06395793e-02  8.97644833e-03
 -2.16666218e-02 -3.90349403e-02  1.56783834e-02  4.90158424e-02
  1.02829104e-02 -1.40257729e-02 -7.82714635e-02 -4.19594049e-02
  4.97718062e-03 -1.97147820e-02 -1.22225191e-02 -2.03673858e-02
 -3.36222723e-02  5.23180999e-02  6.24370878e-04  1.15819974e-02
  2.02652999e-34  4.07035537e-02  2.52484735e-02  4.51186039e-02
  6.06567822e-02  3.35382372e-02 -5.01598641e-02  1.34424334e-02
  1.49852894e-02  1.83794890e-02 -7.26791695e-02 -3.15447487e-02]

Sentence: Sentences can be embedded one by one or in a list
Embedding: [ 5.30692972e-02 -2.92309597e-02 -3.48629057e-02  3.71178500e-02
 -2.06491798e-02  3.95141505e-02  3.82806174e-02 -1.27682276e-02
  4.01308425e-02 -3.31618302e-02  5.40344752e-02  2.86833197e-02
  4.86773625e-02 -4.09214124e-02  1.35087138e-02 -7.89823756e-02
  3.45116705e-02  1.41898198e-02  2.86579598e-02  1.42108323e-02
  5.71262557e-03  4.03002882e-03 -4.32528672e-04  1.32613825e-02
  2.45585572e-02 -3.72597668e-03 -3.66856605e-02 -6.74737897e-03
  2.70378087e-02 -7.24915415e-02 -2.66211871e-02 -1.21500227e-03
  1.63496453e-02 -1.08125508e-01  1.56396879e-06  3.85119170e-02
 -3.65744568e-02 -2.66241524e-02 -4.42642644e-02  1.28964707e-02
 -4.57124822e-02 -9.86377150e-03  3.66597883e-02  1.99020170e-02
 -3.10423709e-02 -7.98464753e-03  3.06468289e-02  5.60650416e-02
  3.99376750e-02  7.10424557e-02 -1.53890690e-02 -1.15560731e-02
 -3.35625634e-02 -1.21928900e-02  4.99053895e-02 -5.15735056e-03
  4.40965639e-03 -3.02439537e-02  1.71414074e-02  8.43129605e-02
  1.82205085e-02  5.54764755e-02  1.47548679e-03 -3.29245664e-02
  4.21681814e-02 -9.37603822e-04 -5.85809238e-02 -5.20686172e-02
 -2.86778864e-02 -1.35771267e-03  5.57454638e-02 -3.44870379e-03
  8.22930131e-03  1.78005472e-02  4.17837836e-02 -3.59115750e-02
 -4.77101281e-02  5.18276356e-02  2.39631021e-03  8.95429961e-03
 -1.05461255e-02  2.30628140e-02 -1.33586470e-02 -2.77345572e-02
 -8.70221294e-03 -2.76096240e-02  1.54275466e-02 -3.63631025e-02
 -3.07375453e-02 -1.30853448e-02 -4.51644920e-02 -5.19663729e-02
 -1.07122101e-02 -2.96762008e-02 -1.88344344e-02  1.86181365e-04
 -6.11914657e-02 -4.36858572e-02  2.32646950e-02 -4.52137329e-02
  4.43051383e-02  3.37998942e-03  7.08045904e-03 -1.64862294e-02
 -3.86305037e-03  7.70357670e-03  5.20850671e-03 -4.81047742e-02
 -8.71500969e-02  5.63321821e-02 -3.46184373e-02 -6.49362877e-02
 -6.03670478e-02  1.00820363e-01 -1.79124288e-02 -3.34641449e-02
 -7.67713487e-02  4.04001884e-02  2.43921094e-02  5.72858676e-02
 -1.02228083e-01 -1.41892675e-02  2.15400495e-02  7.54219815e-02
  1.65044200e-02 -3.70611846e-02 -1.82733443e-02  3.78715731e-02
  5.54993786e-02 -1.25556923e-02 -2.76817870e-03  4.61267680e-02
  6.00364916e-02  1.08816940e-02 -4.00968753e-02  4.56166279e-04
  5.09409457e-02 -9.98592097e-03  1.94878336e-02 -2.86727361e-02
 -3.96843515e-02 -2.18908116e-02 -1.81979164e-02 -1.68056022e-02
  2.00587623e-02  1.62739307e-02 -2.20319862e-03 -3.76455523e-02
  4.80875075e-02  4.84269261e-02 -3.94145884e-02  5.42137288e-02
  3.26795839e-02 -4.09100689e-02 -2.90085766e-02 -4.41765320e-03
  1.31802037e-01  1.82665084e-02  1.95300821e-02  3.47890630e-02
  1.46936262e-02  1.62937492e-03  1.09762382e-02 -3.40340026e-02
 -1.09874560e-02 -1.87672321e-02 -1.46074556e-02  1.55209415e-02
  1.16035929e-02  5.18694483e-02 -6.77465573e-02  7.17767626e-02
  5.71071985e-04  1.00780241e-01  2.97402292e-02  7.68599361e-02
 -2.70825047e-02 -2.82981079e-02  2.63844673e-02  1.89826787e-02
  5.51963486e-02  5.80770560e-02 -2.36045029e-02 -3.55424709e-03
  4.47732508e-02  1.30059095e-02  4.51733731e-02 -1.48819992e-03
  3.71161586e-04 -7.09838197e-02 -8.12217444e-02  2.24215239e-02
  9.87787638e-03 -2.28540935e-02 -3.23205739e-02  1.48220714e-02
 -6.32842407e-02  2.41180509e-02 -7.20812753e-03 -4.88322452e-02
 -1.63202398e-02  4.74644639e-02  3.31185386e-02  5.20119891e-02
 -4.03401293e-02  1.61988735e-02  1.98447295e-02 -4.44590524e-02
 -7.34893000e-03  4.14602682e-02  2.54000593e-02  3.82352285e-02
 -1.86112560e-02  1.03059541e-02 -2.72487360e-03 -6.48471527e-03
  1.57464128e-02  7.69995851e-03 -5.83131425e-02 -8.16838909e-03
  1.04357833e-02  1.48157701e-02  2.85898503e-02  2.68386602e-02
  4.88489009e-02 -1.63715314e-02 -2.59585790e-02  2.13107336e-02
  1.36303222e-02  1.84287911e-03 -1.18286919e-03  1.61538683e-02
  3.39008011e-02 -3.28277936e-03 -7.25702420e-02  1.77836716e-02
 -4.66223471e-02 -9.60184336e-02 -2.85691000e-03 -7.19406679e-02
  9.65526514e-03 -2.02038772e-02  1.02709932e-02  9.99064371e-03
 -4.50545996e-02 -4.10117991e-02  5.24773002e-02  1.77238155e-02
 -1.83203388e-02  3.78855728e-02  6.32861024e-03 -9.39196348e-03
 -1.71741042e-02 -6.68029627e-03  3.51470187e-02 -8.73038452e-03
 -3.93557549e-02  5.24430461e-02 -3.79962586e-02  7.54560158e-03
  2.23104449e-04 -1.84037406e-02 -3.06606479e-02  5.50361583e-03
  2.05302821e-03  7.38577917e-03 -1.85285434e-02 -9.70779061e-02
 -4.05838713e-02  1.18751614e-03 -2.94938888e-02 -3.58579345e-02
  5.24144666e-03  2.25621611e-02  2.33390369e-02 -1.22665735e-02
  1.87965238e-03 -2.53022439e-03  3.55886221e-02  5.62574677e-02
  1.98703967e-02 -5.47781959e-02 -4.74455208e-02 -5.60683059e-03
 -1.47266658e-02  4.90902625e-02  1.11881597e-02 -4.88219112e-02
 -2.34884750e-02  1.24090968e-03  2.09168415e-03  1.16700743e-04
  4.68954444e-02 -7.52938092e-02  8.42009857e-03  6.67412858e-03
  9.45224389e-02  6.83849677e-02  1.09988386e-02  1.04785331e-01
  7.95513112e-03  4.71072551e-03  4.00389768e-02 -1.50033468e-02
  1.92360505e-02  4.28813137e-02 -2.79522091e-02  1.52964387e-02
  2.33377283e-03  3.07833403e-02  6.69831634e-02  1.42553337e-02
 -1.22784348e-02  2.65145861e-02 -1.19549753e-02  5.05978521e-03
 -6.42698184e-02 -7.29812235e-02 -1.57861281e-02  1.55567732e-02
  5.65754585e-02 -1.14565585e-02  1.50640411e-02 -4.02392186e-02
  1.21961813e-02 -2.29834393e-02 -5.19917011e-02  1.79916359e-02
  2.99178138e-02  3.60417739e-02  1.39991594e-02  2.71740761e-02
 -3.77170788e-03 -7.02458015e-03 -1.79233737e-02  4.07175347e-02
  3.52634229e-02  2.35491283e-02  3.31922225e-03 -1.84938051e-02
 -2.69720592e-02 -3.38325836e-02 -2.74990369e-02 -7.27826431e-02
 -6.89629512e-03  1.41594699e-03  5.51614724e-03  1.87288094e-02
 -7.41729736e-02 -1.17666088e-02  3.81386466e-02 -2.71116924e-02
 -4.05930281e-02 -1.51583944e-02 -6.35443628e-02  3.79454605e-02
  4.80102077e-02 -3.77885550e-02 -1.78890973e-02 -4.15388346e-02
  7.09787011e-02  2.44980305e-02 -4.33055758e-02  9.61233377e-02
  7.93620385e-03  1.14486683e-02 -3.94983479e-04 -2.73045581e-02
 -5.88592216e-02  2.26384792e-02 -2.38802796e-03 -1.43096270e-02
 -1.01917377e-02  5.17066494e-02 -3.28357657e-03  1.28039885e-02
  2.82140151e-02  1.05748577e-02 -1.07132001e-02  1.26351938e-02
  4.46664207e-02 -9.85660851e-02  4.36468013e-02  1.68522098e-03
 -4.68538366e-02  8.85110348e-03  4.66209985e-02 -6.30490929e-02
 -5.64432815e-02  5.33321872e-02  3.81146348e-03  1.78617183e-02
 -5.23935817e-02 -1.90261304e-02 -7.93266892e-02  6.89902753e-02
  7.21352827e-03  2.66699400e-02 -1.13266585e-02 -2.58580054e-04
  2.97039561e-02 -3.38875242e-02  1.60172377e-02 -5.94127998e-02
  1.65246110e-02 -1.09897519e-04  1.72724016e-02  1.49703668e-02
 -5.83549589e-02 -6.70123845e-03  5.30948117e-03 -3.27517167e-02
 -1.96900256e-02  1.18450774e-02  1.52674150e-02 -1.80474680e-03
 -1.10481111e-02  1.58273485e-02  2.82351263e-02 -4.50964421e-02
 -2.89856680e-02  6.70567378e-02  5.01304194e-02 -1.61719825e-02
  4.72199917e-03 -4.63220254e-02  2.39873491e-02 -1.47534814e-03
  3.74822342e-03  9.33819357e-03  1.21422322e-03  1.49443862e-03
 -3.17492038e-02 -4.61906120e-02 -6.02457970e-02  9.07511543e-03
  8.58422648e-03 -4.19084132e-02  5.10068238e-02 -7.02106133e-02
 -4.30454575e-02  1.55069930e-02  6.40604049e-02  1.36264954e-02
  5.16172685e-03  3.31754843e-03  1.00099677e-02  1.06380358e-02
 -5.58961257e-02  4.54168282e-02 -3.59140448e-02 -9.71804094e-03

In [21]:
# How many numbers each sentence is being represented with
embeddings[0].shape

(768,)

### Embed each chunk

#### Test out CPU

In [22]:
# %%time

# model.to("cpu")

# for item in tqdm(chunks_over_min_token_len):
#     item["embedding"] = model.encode(item["sentence_chunk"])

#### Test out GPU

In [23]:
%%time

model.to("cuda")

for item in tqdm(chunks_over_min_token_len):
    item["embedding"] = model.encode(item["sentence_chunk"])

  0%|          | 0/1680 [00:00<?, ?it/s]

CPU times: total: 2min 38s
Wall time: 27.8 s

#### Test out GPU with batches

In [28]:
# Create a list of text chunks
text_chunks = [item["sentence_chunk"] for item in chunks_over_min_token_len]

random.sample(text_chunks, k=1)

['An iron supplement is also recommended at this time. Rice is no longer recommended for a first infant food because of its high arsenic content. When cereals are introduced, parents can try baby oats or baby wheat. A guide to infant feeding can be found in the 2019 USDA Infant Nutrition and Feeding Guide at: https://wicworks.fns.usda.gov/ resources/infant-nutrition-and-feeding-guide. Everyday Connection Different cultures have specific food customs. In ancient 838 | Infancy']

In [25]:
len(text_chunks)

1680

In [27]:
%%time

# Embed all texts in batches
text_chunks_embeddings = model.encode(text_chunks, batch_size=16, convert_to_tensor=True)

text_chunks_embeddings

CPU times: total: 1min 18s
Wall time: 13.9 s

tensor([[ 0.0674,  0.0902, -0.0051,  ..., -0.0221, -0.0232,  0.0126],
        [ 0.0552,  0.0592, -0.0166,  ..., -0.0120, -0.0103,  0.0227],
        [ 0.0280,  0.0340, -0.0206,  ..., -0.0054,  0.0213,  0.0313],
        ...,
        [ 0.0771,  0.0098, -0.0122,  ..., -0.0409, -0.0752, -0.0241],
        [ 0.1030, -0.0165,  0.0083,  ..., -0.0574, -0.0283, -0.0295],
        [ 0.0864, -0.0125, -0.0113,  ..., -0.0522, -0.0337, -0.0299]],
       device='cuda:0')

### Save embeddings to file

If the embedding database is very large (e.g. 100k+ chunks), it may be better to use a vector database (e.g. `Weaviate`, `Pinecone`, `Chroma`, etc.) instead of saving to a file.

In [ ]:
# Convert the chunks dict (which contains the embedding for each chunk) into a dataframe to save
text_chunks_embeddings_df = pd.DataFrame(chunks_over_min_token_len)

embeddings_df_path = "text_chunks_embeddings_df.csv" # save path

# Convert the df into a csv and save it
text_chunks_embeddings_df.to_csv(embeddings_df_path, index=False)

### Import and view saved embeddings

In [ ]:
# Import the csv of the embeddings
text_chunks_embeddings_df_loaded = pd.read_csv(embeddings_df_path)
text_chunks_embeddings_df_loaded.head() # print first 5 rows

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding
0,-39,Human Nutrition: 2020 Edition UNIVERSITY OF HA...,308,42,77.00,[ 6.74242899e-02 9.02281404e-02 -5.09547861e-...
1,-38,Human Nutrition: 2020 Edition by University of...,210,30,52.50,[ 5.52156419e-02 5.92139252e-02 -1.66167393e-...
2,-37,Contents Preface University of Hawai‘i at Māno...,766,116,191.50,[ 2.79801823e-02 3.39813717e-02 -2.06426494e-...
3,-36,Lifestyles and Nutrition University of Hawai‘i...,941,144,235.25,[ 6.82566985e-02 3.81274670e-02 -8.46854597e-...
4,-35,The Cardiovascular System University of Hawai‘...,998,152,249.50,[ 3.30264494e-02 -8.49768054e-03 9.57159698e-...